CREATE DATABASE WS_SERVER

USE WS_SERVER

CREATE TABLE USERS 
(
   IDUser 		CHAR(36) PRIMARY KEY DEFAULT(UUID()),
   Username 	VARCHAR(255) UNIQUE NOT NULL,
   Email 		VARCHAR(255) UNIQUE NOT NULL,
   Password 	VARCHAR(255) NOT NULL,
   DisplayName VARCHAR(255),
   Avatar 		VARCHAR(255),
   Cover 		VARCHAR(255),
   IsDeleted 	BOOLEAN NOT NULL DEFAULT FALSE
)
